rem copy /y q:\reenigne\8088\xtserver\xtserver\release\xtserver.exe "j:\program files\apache software foundation\apache2.2\cgi-bin"
rem copy /y q:\reenigne\8088\xtserver\xtserver\release\xtqueue.exe "j:\"
rem copy /y q:\reenigne\8088\xtserver\xtserver\release\xtstatus.exe "j:\program files\apache software foundation\apache2.2\cgi-bin"
rem copy /y q:\reenigne\8088\xtserver\xtserver\release\xtcancel.exe "j:\program files\apache software foundation\apache2.2\cgi-bin"
rem copy /y q:\reenigne\8088\xtserver\xtserver\release\xtkill.exe "j:\t\utils"
rem copy /y q:\reenigne\8088\xtserver\index.html "j:\program files\apache software foundation\apache2.2\htdocs"
rem copy /y q:\reenigne\8088\xtserver\stylesheet.css "j:\program files\apache software foundation\apache2.2\htdocs"
copy /y q:\reenigne\8088\xtserver\index.html "q:\work\website\andrew\xtserver"
copy /y q:\reenigne\8088\xtserver\stylesheet.css "q:\work\website\andrew\xtserver"
copy /y q:\reenigne\8088\xtserver\index.html "j:\t\reenigne\8088\xtserver"
copy /y q:\reenigne\8088\xtserver\stylesheet.css "j:\t\reenigne\8088\xtserver"

