@echo off
call test0.bat
call test1.bat
call test2.bat
call test3.bat
call test4.bat
call test5.bat
call test6.bat
call test7.bat
call test8.bat
call test9.bat
call test10.bat
call test11.bat
call test12.bat
call test13.bat
call test14.bat
call test15.bat
call test16.bat
